steps:
# Retrieve composer auth credentials for accessing private repository
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /usr/bin/bash
  args:
    - '-c'
    - |
      gcloud secrets versions access latest --secret=composer-github-auth > ./auth.json && ls
- name: 'gcr.io/cloud-builders/gcloud'
  timeout: 900s
  entrypoint: /usr/bin/bash
  args:
    - '-c'
    - |
      gcloud beta run deploy ${_RUN_SERVICE} \
        --source . \
        --region ${_GCP_REGION} \
        --port ${_PORT} \
        --set-env-vars ${_ENV_VARS} \
        --set-secrets ${_SECRETS} \
        --concurrency ${_CONCURRENCY} \
        --cpu ${_CPU} \
        --memory ${_MEMORY_MB} \
        --timeout ${_TIMEOUT} \
        --min-instances ${_MIN_INSTANCES} \
        --max-instances ${_MAX_INSTANCES} \
        --ingress internal-and-cloud-load-balancing \
        --vpc-connector ${_VPC_CONNECTOR} \
        --vpc-egress all-traffic \
        --platform managed \
        --no-use-http2 \
        --service-account ${_SERVICE_ACCOUNT} \
        --allow-unauthenticated
# use --image with Artifact Registry and docker steps
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY